title: HyunGyu Baek
url: "https://hyungyu.me"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/sambeak"
footer_text: "HyunGyu Baek"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""

remote_theme: ankitsultana/researcher@gem
